
import React from 'react';

const SectionTitle = ({ children }: { children: React.ReactNode }) => (
    <h3 className="text-xl font-bold text-gray-800 mt-8 mb-3">{children}</h3>
);

const TermsOfServicePage = ({ t }: { t: (key: string) => string }) => {
    return (
        <div className="w-full max-w-4xl mx-auto my-8 animate-fade-in-up text-gray-900">
            <div className="text-center">
                <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold tracking-tight text-shadow-lg bg-clip-text text-transparent bg-gradient-to-r from-pink-500 to-purple-600">
                    Terms of Service
                </h1>
                <p className="mt-4 text-lg text-gray-600 max-w-3xl mx-auto">
                    Simple, clear terms for using our AI-powered YouTube growth tools.
                </p>
            </div>

            <div className="mt-12 bg-white p-6 sm:p-10 rounded-2xl shadow-lg border border-gray-200 text-gray-700 leading-relaxed">
                <p className="text-sm text-gray-500">Last Updated: October 26, 2023</p>

                <SectionTitle>1. Welcome to CreatorTune!</SectionTitle>
                <p>
                    Thank you for using CreatorTune ("the Service"), a free, AI-powered web application designed to help YouTube creators audit their channels and get suggestions for growth. These Terms of Service ("Terms") govern your use of our tool. By accessing or using CreatorTune, you agree to be bound by these Terms.
                </p>
                
                <SectionTitle>2. Who Can Use CreatorTune</SectionTitle>
                <p>
                    You must be at least 13 years old to use the Service. If you are using CreatorTune on behalf of an organization, you agree to these Terms for that organization and confirm that you have the authority to bind it to these terms.
                </p>

                <SectionTitle>3. Fair Use Policy</SectionTitle>
                <p>
                    CreatorTune is a free tool built by a solo founder for the creator community. To keep it running smoothly for everyone, you agree not to:
                </p>
                <ul className="list-disc list-inside mt-4 space-y-2 pl-4">
                    <li>Use automated scripts, bots, or scrapers to access or interact with the Service.</li>
                    <li>Abuse the Service by sending an excessive number of requests.</li>
                    <li>Attempt to reverse-engineer, decompile, or otherwise discover the source code or underlying AI models.</li>
                    <li>Use the Service for any illegal or unauthorized purpose.</li>
                </ul>
                <p className="mt-2">
                    We reserve the right to limit or block access for users who violate this policy.
                </p>

                <SectionTitle>4. Our AI Isn't Perfect (Disclaimer)</SectionTitle>
                <p>
                    The suggestions and analysis provided by CreatorTune are generated by an artificial intelligence model. While we strive to provide helpful and accurate insights, the AI is not perfect and its advice is not guaranteed to be 100% accurate or result in channel growth. The Service is provided "as is" without warranties of any kind.
                </p>

                <SectionTitle>5. Limitation of Liability</SectionTitle>
                <p>
                    As a solo founder providing a free tool, my liability is limited. To the fullest extent permitted by law, CreatorTune (and its founder) shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses, resulting from:
                </p>
                 <ul className="list-disc list-inside mt-4 space-y-2 pl-4">
                    <li>Your access to, use of, or inability to access or use the Service.</li>
                    <li>Any action you take based on the advice or insights provided by the Service.</li>
                    <li>Any conduct or content of any third party on the Service.</li>
                </ul>

                <SectionTitle>6. External Links</SectionTitle>
                <p>
                    CreatorTune may contain links to third-party websites or services (e.g., GitHub, social media profiles) that are not owned or controlled by us. We are not responsible for the content, privacy policies, or practices of any third-party websites.
                </p>

                <SectionTitle>7. Changes to These Terms</SectionTitle>
                <p>
                    We may modify these Terms from time to time. If we make changes, we will update the "Last Updated" date at the top of this page. Your continued use of the Service after any changes constitutes your acceptance of the new Terms.
                </p>

                <SectionTitle>8. Contact Us</SectionTitle>
                <p>
                    If you have any questions about these Terms, please feel free to reach out. I'm always happy to chat with fellow creators!
                    <br />
                    Email: <a href="mailto:sy8936216@gmail.com" className="text-purple-600 font-semibold hover:underline">sy8936216@gmail.com</a>
                </p>
            </div>
        </div>
    );
};

export default TermsOfServicePage;